pipeline {
    agent any
    tools {
        tool  'Maven'
    }
    stages {
        stage('Compilar') {
            steps {
                sh 'mvn clean install -DskipTests'
            }
        }
        stage('Pruebas de Integración') {
            steps {
                sh 'mvn test'
            }
        }
    }
}
